version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:80" # Map host port 80 to container port 80
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000" # Map host port 3000 to container port 3000
    environment:
      DB_HOST: mysql_db
      DB_USER: root     # เรายังคงตั้งค่า user ใน server.js เป็น 'root'
      DB_PASSWORD: password
      DB_NAME: myDatabase
    depends_on:
      - mysql_db
    networks:
      - app-network

  mysql_db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password 
      MYSQL_DATABASE: myDatabase
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: